name: Trigger-Rules-POC-Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  update-algolia:
      uses: ./.github/workflows/update-algolia-index.yml
      secrets: inherit

  trigger-deploy:
    needs: update-algolia
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN:   ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT: ${{ secrets.VERCEL_PROJECT }}
      VERCEL_TEAM:    ${{ secrets.VERCEL_TEAM }}
      REPO_ID:        ${{ secrets.WEBSITE_REPO_ID }}

    steps:
    # 3-1 Determine build target (prod vs preview)
    - id: vars
      run: |
        if [[ "$GITHUB_REF_NAME" == "main" ]]; then
          echo "VERCEL_TARGET=production" >> $GITHUB_OUTPUT
        else
          echo "VERCEL_TARGET=preview"    >> $GITHUB_OUTPUT
        fi
        echo "TINA_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT

    # 3-2 Trigger Vercel build (always compiling website branch `main`)
    - run: |
        curl -fsSL -X POST "https://api.vercel.com/v13/deployments" \
          -H "Authorization: Bearer $VERCEL_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
                "name":      "'"$VERCEL_PROJECT"'",
                "project":   "'"$VERCEL_PROJECT"'",
                "teamId":    "'"$VERCEL_TEAM"'",
                "gitSource": {
                  "type": "github",
                  "repoId": "'"$REPO_ID"'",
                  "ref":  "main"                            # ← always build main
                },
                "build": {
                  "env": { "NEXT_PUBLIC_TINA_BRANCH": "'"${{ steps.vars.outputs.TINA_BRANCH }}"'" }
                },
                "target": "'"${{ steps.vars.outputs.VERCEL_TARGET }}"'"
              }'